export const achievements = [
  {
    id: "cookie_1",
    name: "First Bite",
    description: "Bake 1 cookie.",
    icon: "🍪",
    check: (state) => state.totalCookies >= 1,
  },
  {
    id: "cookie_100",
    name: "Snack Stack",
    description: "Bake 100 cookies.",
    icon: "🍪",
    check: (state) => state.totalCookies >= 100,
  },
  {
    id: "cookie_1k",
    name: "Cookie Rookie",
    description: "Bake 1,000 cookies.",
    icon: "🍪",
    check: (state) => state.totalCookies >= 1000,
  },
  {
    id: "cookie_10k",
    name: "Sugar Rush",
    description: "Bake 10,000 cookies.",
    icon: "🍪",
    check: (state) => state.totalCookies >= 10000,
  },
  {
    id: "cursor_1",
    name: "One Cursor Army",
    description: "Own 1 Cursor.",
    icon: "🖱️",
    check: (state) => state.buildings.cursor >= 1,
  },
  {
    id: "cursor_10",
    name: "Cursor Squad",
    description: "Own 10 Cursors.",
    icon: "🖱️",
    check: (state) => state.buildings.cursor >= 10,
  },
  {
    id: "grandma_1",
    name: "Granny's Touch",
    description: "Hire 1 Grandma.",
    icon: "👵",
    check: (state) => state.buildings.grandma >= 1,
  },
  {
    id: "cps_10",
    name: "Cookie Drip",
    description: "Reach 10 CPS.",
    icon: "⏱️",
    check: (state, derived) => derived.cps >= 10,
  },
  {
    id: "cps_100",
    name: "Bakery Stream",
    description: "Reach 100 CPS.",
    icon: "⏱️",
    check: (state, derived) => derived.cps >= 100,
  },
  {
    id: "cps_1000",
    name: "Cookie River",
    description: "Reach 1,000 CPS.",
    icon: "⏱️",
    check: (state, derived) => derived.cps >= 1000,
  },
];
