export const upgrades = [
  {
    id: "click_add_1",
    name: "Better Oven Mitts",
    description: "+1 cookie per click.",
    cost: 50,
    effect: { type: "click_add", amount: 1 },
  },
  {
    id: "click_add_2",
    name: "Double Dip",
    description: "+2 cookies per click.",
    cost: 500,
    effect: { type: "click_add", amount: 2 },
  },
  {
    id: "click_add_5",
    name: "Choco Shower",
    description: "+5 cookies per click.",
    cost: 2000,
    effect: { type: "click_add", amount: 5 },
  },
  {
    id: "click_mult_2",
    name: "Turbo Clicker",
    description: "Clicks are twice as tasty.",
    cost: 5000,
    effect: { type: "click_mult", amount: 2 },
  },
  {
    id: "click_mult_1_5",
    name: "Sugar Glove",
    description: "Clicks are 1.5x stronger.",
    cost: 15000,
    effect: { type: "click_mult", amount: 1.5 },
  },
  {
    id: "cursor_mult",
    name: "Auto Hand",
    description: "Cursors are twice as efficient.",
    cost: 200,
    effect: { type: "building_mult", amount: 2, target: "cursor" },
  },
  {
    id: "grandma_mult",
    name: "Rolling Pin Pro",
    description: "Grandmas are twice as efficient.",
    cost: 1200,
    effect: { type: "building_mult", amount: 2, target: "grandma" },
  },
  {
    id: "farm_mult",
    name: "Soil of Sugar",
    description: "Farms are twice as efficient.",
    cost: 15000,
    effect: { type: "building_mult", amount: 2, target: "farm" },
  },
  {
    id: "factory_mult",
    name: "Steam Mixers",
    description: "Factories are twice as efficient.",
    cost: 60000,
    effect: { type: "building_mult", amount: 2, target: "factory" },
  },
  {
    id: "bank_mult",
    name: "Sweet Portfolio",
    description: "Banks are twice as efficient.",
    cost: 240000,
    effect: { type: "building_mult", amount: 2, target: "bank" },
  },
  {
    id: "temple_mult",
    name: "Sacred Recipe",
    description: "Temples are twice as efficient.",
    cost: 1200000,
    effect: { type: "building_mult", amount: 2, target: "temple" },
  },
  {
    id: "global_cps",
    name: "Oven Harmony",
    description: "All CPS gains +10% (one-time).",
    cost: 100000,
    effect: { type: "global_cps_mult", amount: 1.1 },
  },
];
